### ISSUE TITLE
what params with auth?

### ISSUE THREAD

**Issue by dcboy** [facebookgo/dvara#16]
# ./dvara --addrs 127.0.0.1:27017
2016/08/24 13:38:18 starting *dvara.ReplicaSet
2016/08/24 13:38:18 ignoring failure against address 127.0.0.1:27017: not authorized on admin to execute command { replSetGetStatus: 1 }
could not connect to any provided addresses: [127.0.0.1:27017]

i found the source with flags ,can't set any auth params?

**Comment by daaku** [comment]
There isn't any auth support, and we're not planning on adding it. Issue #2 is about the same thing.
